CREATE Table IF NOT EXISTS schools(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    address VARCHAR (255) NOT NULL,
    latitude FLOAT NOT NULL,
    logitude FLOAT NOT NULL
);